#!/usr/bin/env python3
"""
Pydantic Models for AURELIA API
"""

from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime
from enum import Enum


class SourceType(str, Enum):
    """Source of concept note"""
    FINTBX = "fintbx"
    WIKIPEDIA = "wikipedia"


class ConceptNote(BaseModel):
    """Structured concept note generated by instructor"""
    concept: str = Field(..., description="The financial concept name")
    definition: str = Field(..., description="Clear definition of the concept")
    key_points: List[str] = Field(..., description="3-5 key points about the concept")
    matlab_functions: Optional[List[str]] = Field(
        default=None,
        description="Relevant MATLAB Financial Toolbox functions"
    )
    examples: Optional[List[str]] = Field(
        default=None,
        description="Code examples or usage examples"
    )
    formulas: Optional[List[str]] = Field(
        default=None,
        description="Mathematical formulas related to the concept"
    )
    related_concepts: Optional[List[str]] = Field(
        default=None,
        description="Related financial concepts"
    )
    practical_applications: Optional[List[str]] = Field(
        default=None,
        description="Real-world applications"
    )


class QueryRequest(BaseModel):
    """Request to query for a concept"""
    concept: str = Field(..., description="Financial concept to query", min_length=1)
    force_refresh: bool = Field(default=False, description="Force regeneration even if cached")


class QueryResponse(BaseModel):
    """Response from query endpoint"""
    concept: str
    note: ConceptNote
    source: SourceType
    cached: bool
    generated_at: Optional[datetime] = None
    cached_at: Optional[datetime] = None
    sources_used: List[str] = Field(default_factory=list, description="Page numbers or URLs")
    relevance_score: Optional[float] = None


class SeedRequest(BaseModel):
    """Request to seed multiple concepts"""
    concepts: List[str] = Field(..., description="List of concepts to seed")
    batch_size: int = Field(default=5, description="Process in batches", ge=1, le=20)
    overwrite: bool = Field(default=False, description="Overwrite existing cached notes")


class SeedResult(BaseModel):
    """Result for a single concept seeding"""
    concept: str
    status: str  # "seeded", "skipped", "failed"
    reason: Optional[str] = None
    score: Optional[float] = None
    sources_count: Optional[int] = None
    error: Optional[str] = None


class SeedResponse(BaseModel):
    """Response from seed endpoint"""
    total: int
    seeded: int
    skipped: int
    failed: int
    details: List[SeedResult]
    duration_seconds: float


class HealthResponse(BaseModel):
    """Health check response"""
    status: str
    timestamp: datetime
    pinecone: str  # "connected" or "disconnected"
    postgres: str  # "connected" or "disconnected"
    components: Dict[str, Any]


class StatsResponse(BaseModel):
    """System statistics"""
    total_cached_concepts: int
    source_breakdown: Dict[str, int]  # {"fintbx": 12, "wikipedia": 3}
    recent_queries: int
    cache_hit_rate: Optional[float] = None